services:
  backend:
    build:
      context: ../backend
    volumes:
      - ../backend:/app
    working_dir: /app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    env_file:
      - ../backend/.env

  frontend:
    build:
      context: ../frontend
      target: dev
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 --port 3000
    ports:
      - '3000:3000'
    volumes:
      - ../frontend/src:/app/src
      - ../frontend/public:/app/public
    env_file:
      - ../frontend/.env

volumes:
  frontend_node_modules:
